sonar.projectKey=nest
sonar.projectName=Nest
sonar.sources=app,components,hooks,lib,public,scripts,prisma,types,quality,.github,proxy.ts,instrumentation.ts,next.config.ts
sonar.tests=tests
sonar.exclusions=prisma/migrations/**,public/**/*.png,public/**/*.jpg,public/**/*.jpeg,public/**/*.webp,public/**/*.ico,public/**/*.woff2
sonar.sourceEncoding=UTF-8
sonar.javascript.node.maxspace=4096
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.coverage.exclusions=**/*.d.ts
sonar.qualitygate.wait=true
sonar.qualitygate.timeout=600
